<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 ./static/calendar-ring.gltf
-->

<script>
	import { Group, MeshBasicMaterial, Color, DoubleSide } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';
	import { onMount, tick } from 'svelte';
	import { interactivity } from '@threlte/extras';
	import { spring } from 'svelte/motion';
	interactivity();
	const scale = spring({
		Jan: 1,
		Feb: 1,
		Mar: 1,
		Apr: 1,
		May: 1,
		Jun: 1,
		Jul: 1,
		Aug: 1,
		Sep: 1,
		Oct: 1,
		Nov: 1,
		Dec: 1
	});

	export const ref = new Group();

	const gltf = useGltf('/calendar-ring.gltf');

	const MONTH_TO_HUE_COLOR = {
		Jan: 0,
		Feb: 30,
		Mar: 60,
		Apr: 90,
		May: 120,
		Jun: 150,
		Jul: 180,
		Aug: 210,
		Sep: 240,
		Oct: 270,
		Nov: 300,
		Dec: 330
	};

	// const component = forwardEventHandlers();
	onMount(() => {
		gltf.then((v) => {
			console.log(v.nodes);
		});
	});
</script>

<T is={ref} dispose={false} {...$$restProps}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		{@const monthNodes = Object.keys(gltf.nodes)
			.filter((key) => key.startsWith('Day_'))
			.reduce((acc, cur) => {
				acc[cur.slice(4, 7)] = [...(acc[cur.slice(4, 7)] || []), gltf.nodes[cur]];
				return acc;
			}, {})}
		{#each Object.entries(monthNodes) as [month, monthNode], montIndex (month)}
			{#each monthNode as dayMesh, dayIndex (dayIndex)}
				{@const sat = 100 - dayIndex * 2}
				{@const hsl = `hsl(${MONTH_TO_HUE_COLOR[month]}, ${sat}%, 50%)`}
				{@const color = new Color(hsl)}
				<!-- scale={$scale[month]}
					on:pointerenter={() => {
						scale.update((x,y)=>{ ...$scale, [month]: 1.1 });
					}}
					on:pointerleave={() => {
						scale.update((x,y)=>{ ...$scale, [month]: 1 });
					}} -->
				<T.Mesh
					geometry={dayMesh.geometry}
					material={new MeshBasicMaterial({
						color,
						side: DoubleSide
					})}
				/>
			{/each}
		{/each}
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
